"use strict";
/* ================= 词组搭配数据（三轮学习流 · 详解卡「词组搭配」） =================
   格式：window.WORD_PHRASES = { 单词: [ ["词组","中文释义"], ... ] }
   每词 3-5 条常用搭配；未收录的词详解卡自动隐藏词组区，按批次向对象追加即可扩充。 */
window.WORD_PHRASES={
"about":[["talk about","谈论"],["about ten minutes","大约十分钟"],["how about...","…怎么样"]],
"accept":[["accept an invitation","接受邀请"],["accept the truth","接受事实"],["accept a gift","收下礼物"]],
"accident":[["by accident","偶然"],["a traffic accident","交通事故"],["avoid an accident","避免事故"]],
"advertisement":[["see an advertisement","看到广告"],["place an advertisement","刊登广告"],["a job advertisement","招聘广告"]],
"advice":[["take my advice","听我的建议"],["a piece of advice","一条建议"],["ask for advice","征求建议"]],
"afraid":[["be afraid of","害怕"],["be afraid to do","不敢做某事"],["don't be afraid","别怕"]],
"agree":[["agree with sb","同意某人"],["agree to sth","同意某事"],["agree on a plan","就计划达成一致"]],
"alive":[["stay alive","活下来"],["be alive and happy","鲜活而快乐"],["keep hope alive","让希望不灭"]],
"allow":[["allow sb to do","允许某人做某事"],["smoking is not allowed","禁止吸烟"],["allow time for","留出时间做"]],
"alone":[["live alone","独居"],["all alone","独自一人"],["leave sb alone","别打扰某人"]],
"along":[["walk along the road","沿路走"],["along with","连同"],["all along","一直"]],
"already":[["already done","已经完成"],["have already eaten","已经吃过"],["not yet, but almost","还没有，但快了"]],
"although":[["although it rained","虽然下雨"],["although small","虽然小"],["although late","虽然迟了"]],
"always":[["always late","总是迟到"],["as always","一如既往"],["not always","未必总是"]],
"among":[["among the trees","在树丛中"],["among friends","在朋友中间"],["among the best","名列前茅"]],
"angry":[["be angry about","为某事生气"],["be angry with sb","生某人的气"],["angry words","气话"]],
"animal":[["a small animal","小动物"],["wild animals","野生动物"],["animal lover","喜爱动物的人"]],
"another":[["another day","改天"],["one after another","一个接一个"],["another one","再来一个"]],
"answer":[["answer the question","回答问题"],["know the answer","知道答案"],["the answer to...","…的答案"]],
"anyone":[["anyone can see","谁都看得出"],["ask anyone","问谁都行"],["if anyone asks","如果有人问"]],
"appear":[["appear suddenly","突然出现"],["it appears that","看起来"],["appear on TV","上电视"]],
"apple":[["an apple a day","一天一苹果"],["apple pie","苹果派"],["bite an apple","咬一口苹果"]],
"area":[["the area around","周围地区"],["a quiet area","安静的区域"],["parking area","停车区"]],
"argue":[["argue with sb","和某人争论"],["argue about money","为钱争吵"],["argue for","为…辩护"]],
"arm":[["arm in arm","手挽手"],["break an arm","摔断手臂"],["hold out one's arm","伸出手臂"]],
"arrive":[["arrive at school","到校"],["arrive home","到家"],["arrive before the bell","铃前赶到"]],
"art":[["an art show","艺术展"],["work of art","艺术品"],["art school","艺术学校"]],
"ask":[["ask a question","提问"],["ask for help","求助"],["ask the way","问路"]],
"asleep":[["fall asleep","入睡"],["be almost asleep","快要睡着"],["sound asleep","酣睡"]],
"attention":[["pay attention","注意"],["attention, please","请注意"],["draw attention","吸引注意"]],
"avoid":[["avoid an accident","避免事故"],["avoid the crowd","避开人群"],["avoid answering","避而不答"]],
"awake":[["be awake","醒着"],["stay awake","保持清醒"],["wide awake","完全清醒"]],
"away":[["run away","跑开"],["far away","遥远"],["give away","赠送；泄露"]],
"baby":[["a baby brother","小弟弟"],["baby food","婴儿食品"],["only a baby","还是个婴儿"]],
"back":[["come back","回来"],["at the back of","在…后面"],["back home","回到家里"]],
"bad":[["bad news","坏消息"],["a bad cold","重感冒"],["not bad","不错"]],
"bag":[["a school bag","书包"],["paper bag","纸袋"],["pack a bag","收拾包"]],
"ball":[["play ball","玩球"],["a ball game","球赛"],["catch the ball","接住球"]],
"bank":[["river bank","河岸"],["at the bank","在银行"],["bank account","银行账户"]],
"baseball":[["play baseball","打棒球"],["a baseball team","棒球队"],["a baseball game","棒球比赛"]],
"basket":[["a basket of","一篮子"],["shopping basket","购物篮"],["at the bottom of his basket","在篮子底部"]],
"bath":[["take a bath","泡澡"],["a hot bath","热水澡"],["bathroom","浴室"]],
"beach":[["by the beach","在海边"],["on the beach","在沙滩上"],["beach holiday","海滩度假"]],
"bear":[["a black bear","黑熊"],["can't bear","无法忍受"],["bear in mind","记住"]],
"beat":[["beat the drum","打鼓"],["beat any boy","胜过任何人"],["heart beats","心跳"]],
"beautiful":[["beautiful weather","好天气"],["a beautiful voice","动听的嗓音"],["beautifully done","干得漂亮"]],
"become":[["become red","变红"],["become a doctor","成为医生"],["become friends","成为朋友"]],
"bed":[["go to bed","上床睡觉"],["make the bed","整理床铺"],["above her bed","在她床头上方"]],
"beef":[["beef soup","牛肉汤"],["roast beef","烤牛肉"],["beef noodles","牛肉面"]],
"before":[["before the bell","铃响之前"],["the day before","前一天"],["before long","不久"]],
"begin":[["begin to do","开始做"],["begin with","以…开始"],["to begin with","首先"]],
"behind":[["behind the building","楼后面"],["fall behind","落后"],["behind the times","过时"]],
"believe":[["believe him","相信他"],["believe in","信任"],["I can't believe it","难以置信"]],
"bell":[["the bell rings","铃响"],["answer the bell","应门铃"],["before the bell","铃响之前"]],
"belong":[["belong to","属于"],["belong in","应归于"],["feel like you belong","有归属感"]],
"below":[["below the bridge","桥下"],["see below","见下文"],["below zero","零下"]],
"beside":[["beside the window","在窗边"],["beside the point","离题"],["sit beside","坐在旁边"]],
"best":[["do one's best","尽全力"],["best friend","最好的朋友"],["the best part","最好的部分"]],
"better":[["had better","最好"],["feel better","好些了"],["better late than never","迟到总比不来好"]],
"between":[["between you and me","你我之间"],["in between","在中间"],["between classes","课间"]],
"beyond":[["beyond the playground","操场那边"],["beyond words","难以言表"],["go beyond","超出"]],
"bicycle":[["ride a bicycle","骑自行车"],["bicycle lane","自行车道"],["by bicycle","骑车"]],
"big":[["a big blue building","蓝色大楼"],["big city","大城市"],["big surprise","大惊喜"]],
"birth":[["give birth","分娩"],["date of birth","出生日期"],["his birth","他的出生"]],
"birthday":[["happy birthday","生日快乐"],["birthday cake","生日蛋糕"],["birthday party","生日会"]],
"bit":[["a bit","一点"],["a bit of","一点儿"],["bite a bit","咬一小口"]],
"bite":[["take a bite","咬一口"],["bite an egg","咬鸡蛋"],["insect bite","虫咬"]],
"bitter":[["a bitter taste","苦味"],["bitter cold","严寒"],["a little bitter","有点苦"]],
"black":[["black coffee","黑咖啡"],["black and white","黑白"],["in the black","盈利"]],
"blind":[["a blind man","盲人"],["turn a blind eye","视而不见"],["blind date","相亲"]],
"blow":[["blow out","吹灭"],["the wind blows","风吹"],["a heavy blow","沉重一击"]],
"blue":[["a blue building","蓝色建筑"],["feel blue","忧郁"],["out of the blue","突然"]],
"board":[["on the board","在板上"],["blackboard","黑板"],["on board","在船上/车上"]],
"boat":[["by boat","乘船"],["a boat shop","船店"],["row a boat","划船"]],
"body":[["healthy body","健康的身体"],["body language","肢体语言"],["keep fit in body and mind","身心健康"]],
"book":[["read a book","读书"],["by the book","照章办事"],["book a ticket","订票"]],
"born":[["be born","出生"],["born in the countryside","生于乡下"],["born to win","天生赢家"]],
"borrow":[["borrow a book","借书"],["borrow money","借钱"],["borrow your crayon","借你的蜡笔"]],
"boss":[["the boss of","…的老板"],["boss around","发号施令"],["ask the boss","问老板"]],
"both":[["both of us","我们俩"],["both...and...","既…又…"],["on both sides","在两边"]],
"bother":[["don't bother","不必麻烦"],["bother sb","打扰某人"],["not bother to do","懒得做"]],
"bottle":[["a bottle of water","一瓶水"],["bottle up","压抑"],["an empty bottle","空瓶子"]],
"bottom":[["at the bottom of","在…底部"],["from the bottom of my heart","由衷地"],["bottom line","底线"]],
"bowl":[["a bowl of soup","一碗汤"],["a rice bowl","饭碗"],["empty bowl","空碗"]],
"box":[["a box of chalk","一盒粉笔"],["lunch box","午餐盒"],["outside the box","跳出框框"]],
"boy":[["a clever boy","聪明的男孩"],["a crazy boy","疯狂的男孩"],["boy friend","男朋友"]],
"brain":[["use your brain","动动脑子"],["brain storm","头脑风暴"],["rack one's brain","绞尽脑汁"]],
"brave":[["be brave","勇敢些"],["brave the storm","顶着风暴"],["bravely face","勇敢面对"]],
"bread":[["a piece of bread","一片面包"],["bread and butter","面包黄油；生计"],["bake bread","烤面包"]],
"break":[["take a break","休息一下"],["break the window","打破窗户"],["before the break","课间之前"]],
"breakfast":[["eat breakfast","吃早饭"],["have breakfast","吃早饭"],["for breakfast","当早餐"]],
"breath":[["take a deep breath","深呼吸"],["out of breath","上气不接下气"],["hold one's breath","屏住呼吸"]],
"bridge":[["cross a bridge","过桥"],["a bridge over the river","河上的桥"],["burn one's bridges","破釜沉舟"]],
"bright":[["a bright mind","聪慧的头脑"],["bright future","光明未来"],["bright and early","一大早"]],
"bring":[["bring a photo","带来照片"],["bring up","抚养；提起"],["bring back","带回；使想起"]],
"brother":[["my little brother","我弟弟"],["elder brother","哥哥"],["brothers and sisters","兄弟姐妹"]],
"brush":[["a hair brush","发刷"],["brush teeth","刷牙"],["brush away","刷掉"]],
"build":[["build a house","盖房子"],["build it day by day","一天天建成"],["build up","增强"]],
"burn":[["burn out","燃尽；累垮"],["burn the paper","烧纸"],["burn one's money","挥霍钱财"]],
"bus":[["catch a bus","赶公交"],["by bus","乘公交"],["bus stop","公交站"]],
"business":[["run a business","经营生意"],["on business","出差"],["business card","名片"]],
"busy":[["be busy at work","忙于工作"],["as busy as a bee","忙得团团转"],["busy day","忙碌的一天"]],
"butter":[["bread with butter","黄油面包"],["peanut butter","花生酱"],["melted butter","融化的黄油"]],
"butterfly":[["a butterfly on its nose","落在鼻子上的蝴蝶"],["butterfly effect","蝴蝶效应"],["flutter like a butterfly","如蝶飞舞"]],
"buy":[["buy some bread","买面包"],["buy a ticket","买票"],["buy and sell","买卖"]],
"cake":[["a birthday cake","生日蛋糕"],["a piece of cake","小菜一碟"],["a dry cake","干蛋糕"]],
"call":[["call from the kitchen","从厨房喊"],["call a taxi","叫出租车"],["so to call it","姑且这么叫"]],
"calm":[["stay calm","保持冷静"],["calm down","冷静下来"],["calm sea","平静的海"]],
"camera":[["take photos with her camera","用相机拍照"],["digital camera","数码相机"],["on camera","上镜"]],
"camp":[["go camping","去露营"],["summer camp","夏令营"],["camp fire","营火"]],
"candy":[["a piece of candy","一颗糖"],["candy shop","糖果店"],["hide a candy","藏一颗糖"]],
"cap":[["a cap from a college","大学的帽子"],["put on a cap","戴上帽子"],["baseball cap","棒球帽"]],
"car":[["by car","开车"],["drive a car","开车"],["car park","停车场"]],
"card":[["a birthday card","生日卡"],["credit card","信用卡"],["ID card","身份证"]],
"care":[["care for people","关心他人"],["take care","保重"],["care about","在乎"]],
"careful":[["be careful","小心"],["a careful cook","细心的厨师"],["carefully listen","仔细听"]],
"carry":[["carry chalk","拿着粉笔"],["carry on","继续"],["carry out","执行"]],
"catch":[["catch a cold","感冒"],["catch the bus","赶上公交"],["catch up with","赶上"]],
"cause":[["cause an accident","引起事故"],["root cause","根本原因"],["cause trouble","惹麻烦"]],
"celebrate":[["celebrate a birthday","庆祝生日"],["celebrate with a concert","以音乐会庆祝"],["celebrate the win","庆祝胜利"]],
"centre":[["the city centre","市中心"],["shopping centre","购物中心"],["centre of attention","焦点"]],
"century":[["in the 21st century","在21世纪"],["for centuries","几个世纪以来"],["turn of the century","世纪之交"]],
"certain":[["be certain about","对…确定"],["a certain person","某人"],["make certain","弄清楚"]],
"chair":[["sit on a chair","坐椅子"],["the chairman","主席"],["a broken chair","坏椅子"]],
"chalk":[["a box of chalk","一盒粉笔"],["carry chalk","拿着粉笔"],["chalkboard","黑板"]],
"chance":[["a good chance","好机会"],["by chance","偶然"],["take a chance","冒个险"]],
"change":[["change one's mind","改变主意"],["change the color","改变颜色"],["small change","零钱"]],
"cheap":[["a cheap ticket","便宜的票"],["cheap and good","价廉物美"],["dirt cheap","非常便宜"]],
"check":[["check the cups","检查杯子"],["check the bill","核对账单"],["check in","入住；报到"]],
"cheer":[["cheer him up","让他振作"],["cheers","干杯"],["cheer for","为…欢呼"]],
"chemistry":[["chemistry class","化学课"],["a chemistry teacher","化学老师"],["study chemistry","学化学"]],
"choose":[["choose a topic","选题目"],["choose the short one","选短的"],["choose to do","选择做"]],
"church":[["go to church","做礼拜"],["an old church","老教堂"],["near the church","在教堂附近"]],
"cinema":[["go to the cinema","看电影"],["a small cinema","小影院"],["at the cinema","在电影院"]],
"circle":[["sit in a circle","围圈坐"],["a circle of friends","朋友圈"],["draw a circle","画圆"]],
"city":[["the capital city","首都"],["city life","城市生活"],["big city","大城市"]],
"class":[["in class","在课上"],["the first class","第一节课"],["after class","课后"]],
"classmate":[["my classmates","我的同学们"],["a new classmate","新同学"],["help classmates","帮助同学"]],
"clean":[["clean the floor","擦地板"],["keep it clean","保持清洁"],["a clean room","干净的房间"]],
"clear":[["clear water","清水"],["clear up","放晴；理清"],["crystal clear","一目了然"]],
"clever":[["a clever boy","聪明的男孩"],["clever hands","巧手"],["clever idea","妙主意"]],
"climb":[["climb a mountain","爬山"],["climb anything","什么都能爬"],["climb up","向上爬"]],
"clock":[["around the clock","昼夜不停"],["the clock strikes","钟敲响"],["five o'clock","五点钟"]],
"close":[["close the door","关门"],["close to","靠近"],["close friend","密友"]],
"cloth":[["a piece of cloth","一块布"],["cotton cloth","棉布"],["wash the cloth","洗抹布"]],
"clothes":[["put on clothes","穿上衣服"],["cotton clothes","棉质衣服"],["wash clothes","洗衣服"]],
"cloud":[["on a cloudy day","在阴天"],["a cloud in the sky","天上的一片云"],["every cloud has a silver lining","黑暗中总有一线光明"]],
"coach":[["the science club coach","科学社教练"],["a bus coach","大巴"],["life coach","人生导师"]],
"coast":[["on the coast","在海岸"],["along the coast","沿海"],["the east coast","东海岸"]],
"coat":[["put on your coat","穿上外套"],["a dry coat","干外套"],["coat and tie","外衣领带"]],
"coffee":[["a cup of coffee","一杯咖啡"],["black coffee","黑咖啡"],["coffee shop","咖啡馆"]],
"cold":[["catch a cold","感冒"],["cold water","冷水"],["in the cold","在寒冷中"]],
"collect":[["collect coins","收集硬币"],["collect stamps","集邮"],["collect information","收集信息"]],
"college":[["go to college","上大学"],["a college club","大学社团"],["college life","大学生活"]],
"colour":[["favourite colour","最喜欢的颜色"],["in colour","彩色的"],["show the colours","亮出本色"]],
"come":[["come back","回来"],["come on","加油"],["come true","实现"]],
"comfortable":[["comfortable clothes","舒服的衣服"],["feel comfortable","感到舒适"],["a comfortable chair","舒服的椅子"]],
"common":[["a common article","常见的文章"],["common sense","常识"],["have nothing in common","毫无共同点"]],
"company":[["a bus company","公交公司"],["keep sb company","陪伴某人"],["in company","在众人面前"]],
"compare":[["compare the two roads","比较两条路"],["compare notes","交流意见"],["compare A with B","把A和B比较"]],
"complete":[["complete the composition","完成作文"],["a complete number","完整数目"],["complete the task","完成任务"]],
"computer":[["on the computer","用电脑"],["computer games","电脑游戏"],["connect his computer","连接电脑"]],
"concert":[["go to a concert","听音乐会"],["celebrate with a concert","以音乐会庆祝"],["a live concert","现场演唱会"]],
"condition":[["in good condition","状况良好"],["living conditions","生活条件"],["on this condition","在这个条件下"]],
"connect":[["connect to the Internet","连网"],["connect...to...","把…连接到…"],["a good connection","连接良好"]],
"consider":[["consider the plan","考虑计划"],["consider doing","考虑做"],["all things considered","综合考虑"]],
"continue":[["continue the conversation","继续交谈"],["continue to do","继续做"],["continue reading","继续读"]],
"control":[["keep control of your money","管好钱"],["out of control","失控"],["under control","在掌控中"]],
"conversation":[["have a conversation","交谈"],["continue their conversation","继续他们的谈话"],["polite conversation","客套话"]],
"cook":[["a careful cook","细心的厨师"],["cook dinner","做饭"],["cook the meals","做饭"]],
"cool":[["stay cool","保持冷静"],["cool water","凉水"],["cool down","降温"]],
"copy":[["copy the map","抄地图"],["copy a common article","套用常见的文章"],["make a copy","复印一份"]],
"corner":[["at the corner shop","在街角小店"],["around the corner","即将来临"],["turn the corner","渡过难关"]],
"correct":[["correct your notes","更正笔记"],["the correct answer","正确答案"],["correct the mistakes","改正错误"]],
"cost":[["it costs little","花费很少"],["cost much","花费很多"],["at all costs","不惜一切代价"]],
"cough":[["cough badly","咳嗽得厉害"],["have a cough","咳嗽"],["cough syrup","止咳糖浆"]],
"count":[["count the students","数学生"],["count on","依靠"],["count down","倒计时"]],
"country":[["in the countryside","在乡下"],["all over the country","全国"],["home country","祖国"]],
"couple":[["a couple of","一对；几个"],["a couple from the club","社团里的一对"],["a happy couple","幸福的一对"]],
"courage":[["have the courage","有勇气"],["take courage","鼓起勇气"],["lose courage","失去勇气"]],
"course":[["of course","当然"],["during the course of","在…期间"],["an English course","英语课程"]],
"cousin":[["my little cousin","我表弟"],["a cousin of mine","我的一个表亲"],["cousin's birthday","表弟的生日"]],
"cover":[["cover the leftover food","把剩菜盖起来"],["be covered with","覆盖着"],["cover the cost","支付费用"]],
"cow":[["milk a cow","挤牛奶"],["a fat cow","肥牛"],["cow milk","牛奶"]],
"crazy":[["a crazy boy","疯狂的男孩"],["be crazy about","痴迷于"],["like crazy","疯狂地"]],
"create":[["create her own","创造属于自己的"],["create jobs","创造就业"],["create a new world","创造新世界"]],
"cry":[["don't cry","别哭"],["cry over","为…哭泣"],["cry for help","呼救"]],
"culture":[["an old culture","古老的文化"],["Chinese culture","中国文化"],["culture shock","文化冲击"]],
"cup":[["a cup of tea","一杯茶"],["the World Cup","世界杯"],["wash a cup","洗杯子"]],
"cut":[["cut the cake","切蛋糕"],["a small cut","小伤口"],["cut down","砍倒；削减"]],
"dance":[["dance to a drum","随着鼓起舞"],["dance party","舞会"],["learn to dance","学跳舞"]],
"danger":[["Danger!","危险！"],["in danger","处于危险中"],["out of danger","脱离危险"]],
"dare":[["dare to pull her back","敢拉她回来"],["dare not ask","不敢问"],["how dare you","你竟敢"]],
"dark":[["the street is dark","街上一片漆黑"],["dark blue","深蓝色"],["in the dark","在黑暗中"]],
"date":[["what's the date","今天几号"],["date of birth","出生日期"],["out of date","过时"]],
"daughter":[["her only daughter","她的独生女"],["mother and daughter","母女"],["a daughter's love","女儿的爱"]],
"day":[["day by day","一天天"],["every day","每天"],["the other day","前几天"]],
"dead":[["dead leaves","枯叶"],["a dead end","死胡同"],["be dead tired","累极了"]],
"dear":[["dear friend","亲爱的朋友"],["oh dear","哎呀"],["dearly love","深爱"]],
"death":[["a matter of life and death","生死攸关"],["to death","极度"],["face death","面对死亡"]],
"decide":[["decide the date","定下日期"],["decide to do","决定做"],["decide for yourself","自己决定"]],
"decision":[["make a decision","做决定"],["a difficult decision","艰难的决定"],["the decision is difficult","决定不易"]],
"deep":[["a deep hole","深坑"],["take a deep breath","深呼吸"],["deep in thought","陷入沉思"]],
"delicious":[["delicious dishes","美味的菜"],["smell delicious","闻起来很香"],["delicious soup","鲜美的汤"]],
"dentist":[["see the dentist","看牙医"],["the dentist's office","牙科诊所"],["afraid of the dentist","怕牙医"]],
"depend":[["depend on yourself","靠自己"],["it depends","看情况"],["depend on sb","依赖某人"]],
"describe":[["describe her idea","描述想法"],["hard to describe","难以形容"],["describe in different words","换种说法描述"]],
"desk":[["at her desk","在书桌前"],["the teacher's desk","讲台"],["desk lamp","台灯"]],
"develop":[["develop new skills","发展新技能"],["develop a habit","养成习惯"],["a developing country","发展中国家"]],
"dialogue":[["a quiet dialogue","安静的对话"],["a dialogue at the desk","书桌前的对话"],["open a dialogue","开启对话"]],
"die":[["die hungry","饿死"],["never die","永存"],["die down","渐渐平息"]],
"difference":[["make a difference","产生影响"],["the difference is small","差别很小"],["tell the difference","分辨差别"]],
"different":[["different words","不同的词"],["be different from","与…不同"],["in different ways","以不同方式"]],
"difficult":[["a difficult decision","艰难的决定"],["find it difficult","觉得难"],["nothing difficult","没什么难的"]],
"dinner":[["at dinner","吃饭时"],["cook dinner","做晚饭"],["dinner is chicken","晚饭是鸡肉"]],
"direction":[["in the direction of","朝…方向"],["a new direction","新方向"],["under the direction of","在…指导下"]],
"dirty":[["a dirty coat","脏外套"],["dirty hands","脏手"],["dirty joke","荤笑话"]],
"discover":[["discover our plan","发现我们的计划"],["discover a new world","发现新世界"],["make a discovery","有所发现"]],
"discuss":[["discuss it tomorrow","明天再谈"],["discuss the plan","讨论计划"],["a heated discussion","热烈的讨论"]],
"disease":[["a serious disease","重病"],["heart disease","心脏病"],["prevent disease","预防疾病"]],
"dish":[["a dish of rice","一盘米饭"],["wash the dishes","洗碗"],["delicious dishes","美味的菜"]],
"distance":[["a long distance","远距离"],["in the distance","在远处"],["keep a distance","保持距离"]],
"divide":[["divide the class in two","把班分成两半"],["divide...into...","把…分成…"],["divide the work","分工"]],
"doctor":[["see a doctor","看医生"],["the doctor said","医生说"],["a kind doctor","好心的医生"]],
"dollar":[["half a dollar","半美元"],["make a dollar","赚一块钱"],["dollars and cents","美元和美分"]],
"door":[["at the door","在门口"],["open the door","开门"],["next door","隔壁"]],
"doubt":[["no doubt","毫无疑问"],["doubt the plan","怀疑计划"],["without doubt","无疑"]],
"draw":[["draw a circle","画圆"],["draw a deep breath","深吸一口气"],["draw her dream school","画梦想中的学校"]],
"dream":[["dream of going abroad","梦想出国"],["a sweet dream","美梦"],["dream come true","梦想成真"]],
"dress":[["a red dress","红裙子"],["wash and dress","洗漱穿衣"],["dress up","打扮"]],
"drink":[["drink warm tea","喝热茶"],["something to drink","喝的"],["drink up","喝完"]],
"drive":[["drive his truck","开卡车"],["on the drive home","开车回家路上"],["drive sb crazy","把某人逼疯"]],
"drop":[["drop her shoes","把鞋放下"],["drop it","别提了"],["drop by","顺路拜访"]],
"dry":[["a dry coat","干外套"],["a dry cake","干蛋糕"],["dry one's hair","吹干头发"]],
"during":[["during the break","课间"],["during December","十二月期间"],["during the day","白天"]],
"duty":[["it is my duty","这是我的责任"],["on duty","值班"],["a sense of duty","责任感"]],
"early":[["early morning","清晨"],["as early as possible","尽早"],["an early bird","早起的人"]],
"eat":[["eat first","先吃"],["eat up","吃光"],["eat out","下馆子"]],
"egg":[["boil an egg","煮蛋"],["add an egg","加个蛋"],["egg fried rice","蛋炒饭"]],
"empty":[["an empty stomach","空肚子"],["empty bowl","空碗"],["an empty street","空荡的街"]],
"encourage":[["encourage sb to do","鼓励某人做"],["words of encouragement","鼓励的话"],["be encouraged by","受到鼓舞"]],
"end":[["at the end of","在…末尾"],["in the end","最后"],["end up","最终"]],
"enemy":[["a common enemy","共同的敌人"],["worst enemy","死敌"],["make enemies","树敌"]],
"enjoy":[["enjoy the meal","享受这顿饭"],["enjoy yourself","玩得开心"],["enjoy reading","喜爱阅读"]],
"enough":[["good enough","足够好"],["old enough","年纪够大"],["enough time","足够的时间"]],
"enter":[["enter the classroom","进教室"],["enter a contest","参赛"],["enter the room","进屋"]],
"evening":[["in the evening","在晚上"],["a cold evening","寒冷的傍晚"],["good evening","晚上好"]],
"event":[["a big event","大事"],["in the event","结果"],["a charity event","慈善活动"]],
"ever":[["ever since","自从"],["hardly ever","几乎不"],["the best ever","有史以来最好"]],
"every":[["every day","每天"],["every child","每个孩子"],["every now and then","偶尔"]],
"exam":[["pass the exam","通过考试"],["a mid-term exam","期中考试"],["exam paper","试卷"]],
"example":[["for example","例如"],["a good example","好榜样"],["follow the example","效仿"]],
"excuse":[["excuse me","打扰一下"],["make an excuse","找借口"],["no excuse","没有借口"]],
"exercise":[["do exercise","锻炼"],["exercise book","练习本"],["take more exercise","多运动"]],
"expect":[["expect a call","等电话"],["as expected","不出所料"],["expect too much","期望过高"]],
"expensive":[["an expensive gift","贵重的礼物"],["too expensive","太贵"],["expensive taste","高消费的爱好"]],
"experience":[["a new experience","新体验"],["work experience","工作经验"],["learn from experience","从经验中学习"]],
"explain":[["explain the plan","解释计划"],["explain why","解释原因"],["explain clearly","解释清楚"]],
"eye":[["keep an eye on","留意"],["in my eyes","在我眼里"],["an eye for an eye","以眼还眼"]],
"face":[["face the difficulty","面对困难"],["on one's face","在脸上"],["face to face","面对面"]],
"fact":[["in fact","事实上"],["the fact is","事实是"],["as a matter of fact","其实"]],
"fail":[["fail the exam","考试不及格"],["fail to do","未能做"],["without fail","务必"]],
"fall":[["fall asleep","入睡"],["fall down","摔倒"],["fall behind","落后"]],
"family":[["his family","他的家人"],["family photo","全家福"],["start a family","成家"]],
"famous":[["be famous for","以…闻名"],["a famous writer","著名作家"],["world-famous","世界闻名"]],
"fast":[["run fast","跑得快"],["fast food","快餐"],["fall fast asleep","酣然入睡"]],
"father":[["my father","我父亲"],["like father like son","有其父必有其子"],["a father of two","两个孩子的父亲"]],
"fear":[["with fear","害怕地"],["fear of failure","怕失败"],["without fear","无所畏惧"]],
"feed":[["feed the cat","喂猫"],["feed on","以…为食"],["feed the birds","喂鸟"]],
"feel":[["feel better","感觉好些"],["feel at home","感到自在"],["feel like doing","想做"]],
"festival":[["the Spring Festival","春节"],["a music festival","音乐节"],["a traditional festival","传统节日"]],
"fever":[["have a fever","发烧"],["a high fever","高烧"],["catch a fever","发烧了"]],
"few":[["a few friends","几个朋友"],["quite a few","相当多"],["few and far between","稀少"]],
"field":[["a cotton field","棉花地"],["in the field","在田野；在领域"],["a field of flowers","花田"]],
"fight":[["fight for","为…而战"],["have a fight","打架"],["fight back","反击"]],
"fill":[["fill the cup","倒满杯子"],["fill in","填写"],["fill up","装满"]],
"film":[["see a film","看电影"],["a famous film","著名电影"],["film star","电影明星"]],
"find":[["find out","查明"],["find the way","找到路"],["find it hard","觉得难"]],
"fine":[["a fine day","晴天"],["that's fine","没关系"],["fine rain","细雨"]],
"finger":[["hurt his finger","弄伤手指"],["point a finger","指责"],["cross one's fingers","祈求好运"]],
"finish":[["finish the homework","完成作业"],["finish line","终点线"],["finish first","率先完成"]],
"fire":[["on fire","着火"],["by candle light","烛光"],["catch fire","着火"]],
"first":[["at first","起初"],["the first day","第一天"],["first of all","首先"]],
"fish":[["go fishing","钓鱼"],["a big fish","大鱼"],["fish and chips","炸鱼薯条"]],
"fit":[["keep fit","保持健康"],["fit in","融入"],["not fit","不合适"]],
"floor":[["clean the floor","擦地板"],["ground floor","一楼"],["wooden floor","木地板"]],
"flower":[["a field of flowers","花田"],["pick flowers","摘花"],["flowers bloom","花开"]],
"fly":[["fly a kite","放风筝"],["fly away","飞走"],["time flies","时光飞逝"]],
"follow":[["follow me","跟我来"],["follow the rules","遵守规则"],["as follows","如下"]],
"food":[["leftover food","剩菜"],["fast food","快餐"],["food and drink","饮食"]],
"fool":[["make a fool of","出洋相"],["April fool","四月愚人"],["fool around","胡闹"]],
"foot":[["on foot","步行"],["at the foot of","在…脚下"],["football","足球"]],
"forget":[["forget to do","忘记做"],["forget about it","别放在心上"],["never forget","永生难忘"]],
"fork":[["a knife and fork","一副刀叉"],["fork road","岔路"],["fork out","掏钱"]],
"form":[["fill in a form","填表"],["in the form of","以…形式"],["form a habit","养成习惯"]],
"free":[["free time","空闲时间"],["for free","免费"],["feel free","随意"]],
"fresh":[["fresh air","新鲜空气"],["fresh food","新鲜食物"],["fresh start","新的开始"]],
"friend":[["good friends","好朋友"],["make friends","交朋友"],["a friend of mine","我的一个朋友"]],
"from":[["from the kitchen","从厨房"],["from now on","从今以后"],["come from","来自"]],
"front":[["in front of","在…前面"],["the front door","前门"],["in the front row","在前排"]],
"fruit":[["fresh fruit","新鲜水果"],["a bowl of fruit","一碗水果"],["fruit juice","果汁"]],
"full":[["be full of","充满"],["full name","全名"],["a full stomach","吃饱的肚子"]],
"fun":[["have fun","玩得开心"],["great fun","很有趣"],["make fun of","取笑"]],
"future":[["in the future","将来"],["a bright future","光明未来"],["future plans","未来计划"]],
"game":[["a ball game","球赛"],["play games","玩游戏"],["the game begins","比赛开始"]],
"garden":[["in the garden","在花园"],["a flower garden","花园"],["garden party","游园会"]],
"gate":[["the school gate","校门口"],["at the gate","在大门口"],["gate keeper","门卫"]],
"get":[["get up","起床"],["get home","到家"],["get better","好起来"]],
"gift":[["a birthday gift","生日礼物"],["give a gift","送礼物"],["a gift from the heart","发自内心的礼物"]],
"girl":[["a clever girl","聪明的女孩"],["a little girl","小女孩"],["girl friend","女朋友"]],
"give":[["give up","放弃"],["give him a coin","给他一枚硬币"],["give a hand","帮个忙"]],
"glad":[["glad to see you","见到你很高兴"],["be glad that","很高兴…"],["glad to help","乐于帮忙"]],
"glass":[["a glass of milk","一杯牛奶"],["glasses","眼镜"],["stained glass","彩绘玻璃"]],
"go":[["go home","回家"],["go to school","上学"],["go on","继续"]],
"goal":[["score a goal","进球"],["life goal","人生目标"],["set a goal","设定目标"]],
"good":[["good heart","好心"],["good at","擅长"],["as good as","几乎一样"]],
"grade":[["a good grade","好成绩"],["grade papers","批改试卷"],["in grade three","在三年级"]],
"grass":[["green grass","绿草"],["on the grass","在草地上"],["grass root","草根"]],
"great":[["great news","好消息"],["a great idea","好主意"],["great fun","很有趣"]],
"green":[["green tea","绿茶"],["green light","绿灯"],["green hand","新手"]],
"ground":[["on the ground","在地上"],["ground floor","一楼"],["stand one's ground","不让步"]],
"group":[["a group of","一组"],["in a group","成群"],["study group","学习小组"]],
"grow":[["grow up","长大"],["grow short","变短"],["grow flowers","种花"]],
"guess":[["guess the answer","猜答案"],["a lucky guess","蒙对了"],["guess what","你猜怎么着"]],
"guest":[["an old guest","老客人"],["guest room","客房"],["welcome the guests","迎客"]],
"gun":[["fire a gun","开枪"],["a toy gun","玩具枪"],["stick to one's gun","坚持立场"]],
"habit":[["a good habit","好习惯"],["get into the habit","养成习惯"],["break the habit","改掉习惯"]],
"hair":[["tidy her hair","整理头发"],["long hair","长发"],["hair brush","发刷"]],
"half":[["half a dollar","半美元"],["half an hour","半小时"],["by half","一半"]],
"hand":[["give a hand","帮个忙"],["hand in","上交"],["on the other hand","另一方面"]],
"hang":[["hang the dress","挂裙子"],["hang out","闲逛"],["hang up","挂断电话"]],
"happen":[["what happened","发生了什么"],["happen to do","碰巧"],["as it happens","碰巧"]],
"happy":[["happy birthday","生日快乐"],["be happy with","对…满意"],["happy ending","圆满结局"]],
"hard":[["hard work","辛苦的工作"],["hardly ever","几乎不"],["try hard","努力"]],
"hate":[["hate the rain","讨厌下雨"],["hate to do","讨厌做"],["love and hate","爱与恨"]],
"have":[["have a good time","玩得开心"],["have to","必须"],["have lunch","吃午饭"]],
"head":[["nod his head","点头"],["head teacher","校长"],["keep a cool head","保持冷静"]],
"health":[["good health","健康"],["in poor health","身体不好"],["health food","保健食品"]],
"healthy":[["healthy body","健康的身体"],["stay healthy","保持健康"],["healthy food","健康食品"]],
"hear":[["hear the news","听到消息"],["hear from","收到…的信"],["hear of","听说"]],
"heart":[["a good heart","好心"],["by heart","用心记"],["heart to heart","交心的"]],
"heavy":[["heavy rain","大雨"],["a heavy box","重箱子"],["heavy traffic","拥堵的交通"]],
"help":[["help him","帮助他"],["with the help of","在…帮助下"],["can't help doing","忍不住"]],
"hide":[["hide a candy","藏糖"],["hide and seek","捉迷藏"],["hide the truth","隐瞒真相"]],
"high":[["high school","高中"],["in high spirits","情绪高涨"],["a high fever","高烧"]],
"hold":[["hold my hand","牵我的手"],["hold on","等一下"],["hold a meeting","开会"]],
"holiday":[["on holiday","度假"],["a school holiday","学校假期"],["public holiday","法定假日"]],
"home":[["at home","在家"],["go home","回家"],["home town","家乡"]],
"homework":[["do homework","做作业"],["finish the homework","完成作业"],["hand in homework","交作业"]],
"honest":[["an honest man","诚实的人"],["to be honest","老实说"],["honest answer","诚实的回答"]],
"hope":[["I hope so","希望如此"],["hope for the best","往好处想"],["give up hope","放弃希望"]],
"horse":[["ride a horse","骑马"],["a black horse","黑马"],["eat like a horse","饭量大"]],
"hospital":[["go to hospital","去医院"],["in hospital","住院"],["a city hospital","市医院"]],
"hot":[["hot weather","热天"],["hot tea","热茶"],["hot dog","热狗"]],
"hour":[["an hour ago","一小时前"],["half an hour","半小时"],["office hours","办公时间"]],
"house":[["a big house","大房子"],["at the house","在房子里"],["house work","家务"]],
"how":[["how about","怎么样"],["how much","多少钱"],["how long","多久"]],
"huge":[["a huge success","巨大成功"],["huge amount","巨量"],["a huge house","大房子"]],
"human":[["human being","人类"],["human nature","人性"],["human rights","人权"]],
"hundred":[["hundreds of","数以百计"],["one hundred","一百"],["a hundred percent","百分之百"]],
"hurry":[["in a hurry","匆忙"],["hurry up","快点"],["no hurry","不急"]],
"hurt":[["hurt his finger","弄伤手指"],["feel hurt","感到受伤"],["get hurt","受伤"]],
"husband":[["her husband","她丈夫"],["husband and wife","夫妻"],["a good husband","好丈夫"]],
"ice":[["ice cream","冰淇淋"],["on ice","冰上"],["break the ice","打破僵局"]],
"idea":[["a good idea","好主意"],["have no idea","不知道"],["describe her idea","描述想法"]],
"important":[["important news","重要消息"],["it's important to","…很重要"],["more important","更重要"]],
"improve":[["improve skills","提高技能"],["improve quickly","进步很快"],["room for improvement","改进空间"]],
"interest":[["a place of interest","名胜"],["show interest","表现出兴趣"],["in the interest of","为了…的利益"]],
"interested":[["be interested in","对…感兴趣"],["interested in art","对艺术感兴趣"],["not interested","不感兴趣"]],
"introduce":[["introduce yourself","自我介绍"],["introduce...to...","把…介绍给…"],["a brief introduction","简要介绍"]],
"invite":[["invite sb to do","邀请某人做"],["invite friends","邀请朋友"],["an invitation","邀请函"]],
"job":[["a good job","好工作"],["find a job","找工作"],["on the job","在工作"]],
"join":[["join the club","加入社团"],["join us","加入我们"],["join in","参加"]],
"joke":[["tell a joke","讲笑话"],["a dark joke","黑色笑话"],["play a joke on","捉弄"]],
"journey":[["a long journey","长途旅行"],["start a journey","启程"],["a safe journey","一路平安"]],
"joy":[["with joy","高兴地"],["tears of joy","喜极而泣"],["full of joy","充满欢乐"]],
"judge":[["judge a book by its cover","以貌取人"],["don't judge","别妄下判断"],["a fair judge","公正的裁判"]],
"juice":[["fruit juice","果汁"],["a glass of juice","一杯果汁"],["orange juice","橙汁"]],
"jump":[["jump up","跳起来"],["jump for joy","欢欣雀跃"],["jump into","跳入"]],
"just":[["just now","刚才"],["just then","就在那时"],["just a little","只有一点"]],
"keep":[["keep control","保持掌控"],["keep quiet","保持安静"],["keep a secret","保守秘密"]],
"key":[["the key to the door","门的钥匙"],["a key question","关键问题"],["low key","低调"]],
"kick":[["kick the ball","踢球"],["kick off","开始"],["kick out","逐出"]],
"kill":[["kill time","消磨时间"],["kill two birds with one stone","一石二鸟"],["dressed to kill","打扮得极为动人"]],
"kind":[["a kind behaviour","善良的行为"],["kind of","有点"],["all kinds of","各种各样的"]],
"kiss":[["kiss goodbye","吻别"],["blow a kiss","飞吻"],["kiss the baby","亲吻宝宝"]],
"kitchen":[["from the kitchen","从厨房"],["kitchen table","餐桌"],["in the kitchen","在厨房里"]],
"kite":[["fly a kite","放风筝"],["a paper kite","纸风筝"],["high as a kite","飞得极高"]],
"knee":[["hurt my knee","伤到膝盖"],["bend the knee","屈膝"],["on one's knees","跪着"]],
"knife":[["a knife and fork","一副刀叉"],["a sharp knife","锋利的刀"],["knife edge","刀刃边缘"]],
"know":[["know the answer","知道答案"],["as you know","如你所知"],["get to know","认识"]],
"lab":[["science lab","科学实验室"],["in the lab","在实验室"],["language lab","语音室"]],
"lady":[["an old lady","老妇人"],["a young lady","年轻女士"],["lady first","女士优先"]],
"lake":[["by the lake","在湖边"],["a small lake","小湖"],["lake water","湖水"]],
"lamp":[["a desk lamp","台灯"],["street lamp","路灯"],["lamp light","灯光"]],
"land":[["on land","在陆地上"],["land on","降落"],["a piece of land","一块地"]],
"language":[["a foreign language","外语"],["body language","肢体语言"],["language learning","语言学习"]],
"large":[["a large number","大量"],["a large house","大房子"],["at large","逍遥法外"]],
"last":[["last week","上周"],["at last","终于"],["last for an hour","持续一小时"]],
"late":[["almost late","差点迟到"],["stay up late","熬夜"],["better late than never","迟做总比不做好"]],
"laugh":[["laugh at","嘲笑"],["laugh out loud","大笑"],["everyone laughs","大家都笑"]],
"law":[["break the law","违法"],["by law","依法"],["a law student","法学学生"]],
"lazy":[["a lazy afternoon","慵懒的下午"],["lazy bones","懒骨头"],["too lazy to move","懒得动"]],
"lead":[["lead the way","带路"],["lead to","导致"],["lead a happy life","过幸福生活"]],
"leaf":[["a green leaf","绿叶"],["turn over a new leaf","翻开新的一页"],["dead leaves","枯叶"]],
"learn":[["learn English","学英语"],["learn from","向…学习"],["learn by heart","背熟"]],
"leave":[["leave for school","动身去学校"],["leave behind","落下；留下"],["leave alone","别管"]],
"left":[["on the left","在左边"],["turn left","左转"],["left over","剩余的"]],
"leg":[["break a leg","祝演出成功"],["long legs","长腿"],["stretch one's legs","伸伸腿"]],
"lend":[["lend a hand","帮个忙"],["lend me your book","借我书"],["lend an ear","倾听"]],
"lesson":[["the first lesson","第一课"],["teach sb a lesson","给某人教训"],["learn a lesson","吸取教训"]],
"letter":[["write a letter","写信"],["a love letter","情书"],["to the letter","不折不扣"]],
"library":[["in the library","在图书馆"],["school library","学校图书馆"],["library book","图书馆的书"]],
"lie":[["lie down","躺下"],["tell a lie","说谎"],["lie in bed","卧床"]],
"life":[["daily life","日常生活"],["all my life","一生"],["life is beautiful","生活是美好的"]],
"lift":[["lift up","举起"],["take the lift","坐电梯"],["give sb a lift","捎某人一程"]],
"light":[["a candle light","烛光"],["turn on the light","开灯"],["light rain","小雨"]],
"like":[["would like","想要"],["look like","看起来像"],["something like","诸如"]],
"line":[["wait in line","排队"],["draw a line","画线"],["in line with","与…一致"]],
"lion":[["a brave lion","勇敢的狮子"],["lion dance","舞狮"],["the lion's share","最大的一份"]],
"lip":[["lip service","空口说白话"],["bite one's lip","咬嘴唇"],["a word on everyone's lips","众口相传的话"]],
"list":[["a shopping list","购物清单"],["make a list","列清单"],["a list of words","单词表"]],
"listen":[["listen to","听"],["listen carefully","仔细听"],["listen to music","听音乐"]],
"little":[["a little","一点"],["little sister","小妹妹"],["little by little","一点一点"]],
"live":[["live alone","独居"],["live a happy life","过幸福生活"],["live with","与…同住"]],
"lonely":[["feel lonely","感到孤独"],["a lonely road","人迹罕至的路"],["lonely hearts","寂寞的心"]],
"long":[["all day long","一整天"],["no longer","不再"],["as long as","只要"]],
"look":[["look at","看"],["look for","寻找"],["look after","照顾"]],
"lose":[["lose the game","输了比赛"],["lose weight","减肥"],["lose heart","灰心"]],
"love":[["fall in love","坠入爱河"],["with love","以爱"],["love story","爱情故事"]],
"low":[["in a low voice","低声"],["low price","低价"],["run low","快用完"]],
"luck":[["good luck","好运"],["by luck","碰巧"],["tough luck","倒霉"]],
"lunch":[["eat lunch","吃午饭"],["lunch box","午餐盒"],["at lunch","吃午饭时"]],
"machine":[["a washing machine","洗衣机"],["answer machine","答录机"],["by machine","用机器"]],
"mail":[["e-mail","电子邮件"],["by mail","邮寄"],["mail box","邮箱"]],
"make":[["make the bed","整理床铺"],["make friends","交朋友"],["make up","编造；和解"]],
"man":[["a young man","年轻男子"],["a polite man","有礼貌的人"],["man and wife","结为夫妻"]],
"manage":[["manage a shop","经营店铺"],["manage to do","设法做到"],["manage time","管理时间"]],
"map":[["an ancient map","古老的地图"],["copy the map","抄地图"],["a map of Asia","亚洲地图"]],
"mark":[["a high mark","高分"],["mark the words","标注词语"],["leave a mark","留下印记"]],
"market":[["the fruit market","水果市场"],["at the market","在市场"],["market price","市场价"]],
"marry":[["marry sb","与某人结婚"],["get married","结婚"],["married couple","已婚夫妇"]],
"match":[["a football match","足球赛"],["match the words","匹配单词"],["find one's match","棋逢对手"]],
"matter":[["what's the matter","怎么了"],["it doesn't matter","没关系"],["as a matter of fact","事实上"]],
"meal":[["a delicious meal","美味的一餐"],["after the meal","饭后"],["three meals a day","一日三餐"]],
"mean":[["mean it","是认真的"],["what do you mean","什么意思"],["mean a lot","意义重大"]],
"meat":[["eat meat","吃肉"],["fresh meat","鲜肉"],["meat ball","肉丸"]],
"medicine":[["take medicine","吃药"],["a small drug in a paper bag","纸袋里的药"],["Chinese medicine","中药"]],
"meet":[["meet friends","见朋友"],["meet the need","满足需要"],["meet up","碰头"]],
"meeting":[["attend a meeting","开会"],["a class meeting","班会"],["sports meeting","运动会"]],
"member":[["a club member","社团成员"],["family member","家庭成员"],["member card","会员卡"]],
"memory":[["in memory of","纪念"],["a sweet memory","甜蜜的回忆"],["lose one's memory","失忆"]],
"mention":[["don't mention it","不客气"],["as mentioned above","如上所述"],["mention the plan","提到计划"]],
"message":[["leave a message","留言"],["a text message","短信"],["take a message","捎口信"]],
"middle":[["in the middle of","在…中间"],["middle school","中学"],["the middle one","中间那个"]],
"mile":[["walk for miles","走了几英里"],["miles away","几英里外"],["go the extra mile","加倍努力"]],
"milk":[["a glass of milk","一杯牛奶"],["milk tea","奶茶"],["cow's milk","牛奶"]],
"mind":[["change one's mind","改变主意"],["keep in mind","记住"],["never mind","没关系"]],
"minute":[["ten minutes","十分钟"],["in a minute","马上"],["wait a minute","等一下"]],
"miss":[["miss the bus","错过公交"],["miss you","想你"],["miss out","错过"]],
"mistake":[["make a mistake","犯错"],["by mistake","弄错"],["learn from mistakes","从错误中学习"]],
"modern":[["modern life","现代生活"],["modern art","现代艺术"],["modern times","现代"]],
"moment":[["at the moment","此刻"],["for a moment","一会儿"],["at any moment","随时"]],
"money":[["save money","存钱"],["spend money","花钱"],["pocket money","零花钱"]],
"month":[["last month","上个月"],["every month","每月"],["month by month","逐月"]],
"moon":[["a full moon","满月"],["moon light","月光"],["once in a blue moon","千载难逢"]],
"morning":[["every morning","每天早晨"],["an April morning","四月的早晨"],["good morning","早上好"]],
"mother":[["her mother","她母亲"],["mother tongue","母语"],["like a mother","像母亲一样"]],
"mountain":[["climb a mountain","爬山"],["a high mountain","高山"],["mountain top","山顶"]],
"mouth":[["open your mouth","张嘴"],["mouth to mouth","口对口"],["shut one's mouth","闭嘴"]],
"move":[["move house","搬家"],["move on","继续前进"],["move away","搬走"]],
"movie":[["see a movie","看电影"],["a funny movie","有趣的电影"],["movie star","电影明星"]],
"music":[["listen to music","听音乐"],["pop music","流行音乐"],["a piece of music","一段乐曲"]],
"must":[["must be","一定是"],["must do","必须做"],["must have done","一定做了"]],
"name":[["full name","全名"],["name the cat","给猫取名"],["in the name of","以…名义"]],
"nature":[["human nature","人性"],["in nature","在自然界"],["by nature","天生"]],
"near":[["near the window","靠窗"],["in the near future","不久的将来"],["near and dear","亲密的"]],
"necessary":[["if necessary","如有必要"],["not necessary","不必要"],["necessary for","对…是必要的"]],
"neck":[["neck and neck","不分上下"],["a stiff neck","僵直的脖子"],["risk one's neck","冒生命危险"]],
"need":[["need help","需要帮助"],["in need","需要中"],["no need","不必"]],
"neighbour":[["my neighbour","我的邻居"],["next-door neighbour","隔壁邻居"],["neighbour hood","街区"]],
"never":[["never give up","永不放弃"],["never mind","没关系"],["never before","从未"]],
"new":[["new friends","新朋友"],["a new start","新开始"],["brand new","全新"]],
"news":[["good news","好消息"],["a piece of news","一条新闻"],["no news is good news","没消息就是好消息"]],
"next":[["next week","下周"],["next to","紧挨着"],["the next day","第二天"]],
"nice":[["nice weather","好天气"],["a nice person","好人"],["nice to meet you","很高兴见到你"]],
"night":[["at night","在夜里"],["all night","整夜"],["day and night","日日夜夜"]],
"nod":[["nod your head","点头"],["nod in agreement","点头赞同"],["nod by the fire","炉火旁打盹"]],
"noise":[["make a noise","制造噪音"],["a strange noise","怪声"],["noise pollution","噪音污染"]],
"none":[["none of them","他们中无人"],["none other than","正是"],["second to none","首屈一指"]],
"noon":[["at noon","在中午"],["by noon","到中午"],["high noon","正午"]],
"normal":[["a normal day","平常的一天"],["back to normal","恢复正常"],["normal temperature","正常体温"]],
"north":[["in the north","在北方"],["north wind","北风"],["up north","去北方"]],
"nose":[["a runny nose","流鼻涕"],["on its nose","在它鼻子上"],["follow one's nose","凭直觉走"]],
"note":[["take notes","记笔记"],["correct your notes","更正笔记"],["a thank-you note","感谢信"]],
"notice":[["take notice of","注意到"],["on short notice","临时通知"],["public notice","公告"]],
"number":[["a large number of","大量"],["phone number","电话号码"],["complete number","完整数目"]],
"nurse":[["a kind nurse","好心的护士"],["see a nurse","看护士"],["hospital nurse","医院护士"]],
"ocean":[["the Pacific Ocean","太平洋"],["an ocean of","大量"],["ocean blue","海蓝"]],
"offer":[["offer help","提供帮助"],["offer a job","提供工作"],["special offer","特价"]],
"office":[["at the office","在办公室"],["ask at the office","到办公室问"],["post office","邮局"]],
"often":[["how often","多久一次"],["more often","更经常"],["as often as","每当"]],
"old":[["an old friend","老朋友"],["an old culture","古老的文化"],["the old days","过去"]],
"once":[["at once","立刻"],["once upon a time","从前"],["once more","再一次"]],
"one":[["one by one","一个接一个"],["one day","有一天"],["one another","互相"]],
"only":[["only child","独生子女"],["not only...but also","不仅…而且"],["only if","只有"]],
"open":[["open the door","开门"],["open your eyes","睁眼"],["in the open air","在户外"]],
"orange":[["an orange juice","橙汁"],["orange color","橙色"],["orange peel","橘子皮"]],
"order":[["in order","整齐；按序"],["in order to","为了"],["keep order","维持秩序"]],
"other":[["the other day","前几天"],["other people","其他人"],["each other","互相"]],
"out":[["go out","出去"],["out of","在…外"],["find out","查明"]],
"outside":[["outside the desk","在书桌外"],["go outside","出去"],["outside the window","窗外"]],
"over":[["over there","在那边"],["all over","到处"],["game over","结束"]],
"own":[["my own","我自己的"],["on one's own","独自"],["of one's own","属于自己"]],
"page":[["turn the page","翻页"],["page after page","一页又一页"],["an article about Australia","一篇关于澳大利亚的文章"]],
"pain":[["no pain no gain","不劳无获"],["in pain","疼痛"],["a pain in the neck","眼中钉"]],
"paint":[["paint the wall","刷墙"],["a wet paint","油漆未干"],["paint a picture","画画"]],
"pair":[["a pair of","一双"],["in pairs","成对"],["a pair of chopsticks","一双筷子"]],
"paper":[["a piece of paper","一张纸"],["paper bag","纸袋"],["on paper","在纸面上"]],
"parent":[["her parents","她父母"],["parent meeting","家长会"],["single parent","单亲"]],
"park":[["in the park","在公园"],["car park","停车场"],["park a car","停车"]],
"part":[["take part in","参加"],["part of","一部分"],["for my part","就我而言"]],
"party":[["a birthday party","生日会"],["party time","派对时间"],["join the party","加入聚会"]],
"pass":[["pass the exam","通过考试"],["pass by","路过"],["pass on","传递"]],
"past":[["in the past","过去"],["past ten","十点过后"],["forget the past","忘记过去"]],
"path":[["a stone path","石径"],["on the path","在小路上"],["cross one's path","不期而遇"]],
"patient":[["be patient","耐心点"],["a patient man","有耐心的人"],["patient with","对…耐心"]],
"pay":[["pay attention","注意"],["pay for","付款"],["pay back","偿还"]],
"peace":[["in peace","和平地"],["a piece of peace","一刻安宁"],["peace of mind","内心平静"]],
"pen":[["a pen friend","笔友"],["pen and paper","笔和纸"],["sign with a pen","用笔签名"]],
"people":[["young people","年轻人"],["people around","周围的人"],["of all people","偏偏"]],
"photo":[["take photos","拍照"],["a photo of","…的照片"],["in the photo","在照片里"]],
"piano":[["play the piano","弹钢琴"],["piano lesson","钢琴课"],["a piano concert","钢琴音乐会"]],
"pick":[["pick up","捡起；接"],["pick a topic","选题目"],["pick out","挑出"]],
"picnic":[["go for a picnic","去野餐"],["a family picnic","家庭野餐"],["picnic basket","野餐篮"]],
"picture":[["a picture of","…的图片"],["take a picture","拍照"],["in the picture","在图中"]],
"piece":[["a piece of bread","一片面包"],["a piece of cake","小菜一碟"],["piece by piece","一点一点"]],
"place":[["take place","发生"],["a quiet place","安静的地方"],["in the first place","起初"]],
"plan":[["make a plan","做计划"],["plan a trip","计划旅行"],["plan for the future","规划未来"]],
"plane":[["by plane","坐飞机"],["catch a plane","赶飞机"],["paper plane","纸飞机"]],
"plant":[["a power plant","发电厂"],["plant a tree","种树"],["plant flowers","种花"]],
"plate":[["on her plate","在她盘子里"],["a plate of","一盘"],["clean plate","吃光盘子"]],
"play":[["play the piano","弹钢琴"],["play with","和…玩"],["play a role","扮演角色；起作用"]],
"please":[["please sit down","请坐"],["as you please","随意"],["please yourself","请自便"]],
"pleasure":[["with pleasure","乐意效劳"],["my pleasure","我的荣幸"],["for pleasure","为了消遣"]],
"pocket":[["pocket money","零花钱"],["in his pocket","在他口袋里"],["out of pocket","自掏腰包"]],
"point":[["point out","指出"],["point to","指向"],["to the point","切中要点"]],
"police":[["call the police","报警"],["the police station","警察局"],["police officer","警官"]],
"polite":[["a polite man","有礼貌的人"],["polite conversation","客套话"],["be polite to","对…礼貌"]],
"pool":[["a swimming pool","游泳池"],["a pool of water","一滩水"],["car pool","拼车"]],
"poor":[["a poor man","穷苦人"],["poor health","体弱"],["poor thing","可怜的家伙"]],
"position":[["in a good position","处于有利位置"],["apply for a position","申请职位"],["sit in this position","保持这个坐姿"]],
"possible":[["as soon as possible","尽快"],["if possible","如果可能"],["not possible","不可能"]],
"post":[["post a letter","寄信"],["post office","邮局"],["post the news","发布消息"]],
"potato":[["a hot potato","棘手问题"],["mashed potato","土豆泥"],["small potatoes","小人物"]],
"practice":[["practice English","练习英语"],["practice makes perfect","熟能生巧"],["in practice","实践中"]],
"praise":[["praise the food","称赞食物"],["high praise","高度赞扬"],["sing one's own praise","自夸"]],
"prefer":[["prefer tea to coffee","茶比咖啡更喜欢"],["prefer to do","宁愿做"],["would rather","宁愿"]],
"prepare":[["prepare the lesson","备课"],["prepare for","为…准备"],["prepare a meal","准备一餐"]],
"present":[["at present","目前"],["a birthday present","生日礼物"],["present the plan","展示计划"]],
"pretty":[["pretty good","相当好"],["a pretty girl","漂亮的女孩"],["pretty soon","很快"]],
"prevent":[["prevent disease","预防疾病"],["prevent sb from doing","阻止某人做"],["prevent an accident","防止事故"]],
"price":[["the price of","…的价格"],["at a low price","低价"],["priceless","无价的"]],
"pride":[["take pride in","以…为豪"],["a sense of pride","自豪感"],["hurt one's pride","伤自尊"]],
"print":[["print out","打印出来"],["in print","已出版"],["finger print","指纹"]],
"prize":[["win a prize","获奖"],["the first prize","一等奖"],["a prize for","…的奖项"]],
"problem":[["no problem","没问题"],["solve the problem","解决问题"],["a big problem","大问题"]],
"promise":[["make a promise","许诺"],["keep a promise","守诺"],["promise to do","承诺做"]],
"protect":[["protect the environment","保护环境"],["protect...from...","保护…免受…"],["protected by","受…保护"]],
"proud":[["be proud of","为…骄傲"],["proud look","得意的神情"],["do sb proud","给某人争光"]],
"prove":[["prove the truth","证明真相"],["prove it","证明一下"],["prove useful","证明有用"]],
"public":[["in public","公开地"],["public school","公立学校"],["the public","公众"]],
"pull":[["pull her back","拉她回来"],["pull up","停下"],["pull out","拔出"]],
"punish":[["punish sb for","因…惩罚"],["be punished","受罚"],["punish the lazy","惩罚懒惰"]],
"pupil":[["a quiet pupil","安静的学生"],["pupil's desk","课桌"],["top pupil","尖子生"]],
"purpose":[["on purpose","故意"],["for the purpose of","为了"],["serve the purpose","达到目的"]],
"push":[["push the door","推门"],["push on","继续"],["push up","推高"]],
"put":[["put on","穿上"],["put up","张贴；搭建"],["put off","推迟"]],
"question":[["ask a question","提问"],["no question","毫无疑问"],["out of the question","不可能"]],
"quick":[["a quick look","快速一瞥"],["be quick","快点"],["quick lunch","快手午餐"]],
"quiet":[["keep quiet","保持安静"],["a quiet boy","安静的男孩"],["a quiet dialogue","安静的对话"]],
"rain":[["heavy rain","大雨"],["in the rain","在雨中"],["rain or shine","风雨无阻"]],
"reach":[["reach the top","到达顶端"],["reach out","伸出"],["out of reach","够不着"]],
"read":[["read a book","读书"],["read aloud","朗读"],["read about","读到"]],
"ready":[["be ready","准备好"],["get ready for","为…准备"],["ready-made","现成的"]],
"real":[["the real reason","真正原因"],["for real","真的"],["real life","现实生活"]],
"reason":[["the real reason","真正原因"],["by reason of","由于"],["listen to reason","听从道理"]],
"remember":[["remember me","记得我"],["remember to do","记得做"],["remember well","记得清楚"]],
"remind":[["remind sb of","使某人想起"],["remind me to do","提醒我做"],["a gentle reminder","温心提示"]],
"remove":[["remove the stain","去除污渍"],["remove the dust","除去灰尘"],["move to a new home","搬新家"]],
"repair":[["repair the bike","修自行车"],["under repair","维修中"],["repair shop","修理店"]],
"repeat":[["repeat the word","重复单词"],["repeat after me","跟我读"],["history repeats","历史重演"]],
"reply":[["reply to","回复"],["a quick reply","快速回复"],["reply in return","答复"]],
"rest":[["take a rest","休息"],["the rest of","其余的"],["rest area","休息区"]],
"restaurant":[["a small restaurant","小餐馆"],["at the restaurant","在餐馆"],["a Chinese restaurant","中餐馆"]],
"result":[["as a result","结果"],["the result of","…的结果"],["without result","徒劳"]],
"return":[["in return","作为回报"],["return home","回家"],["return the book","还书"]],
"rich":[["a rich man","富人"],["rich in","富含"],["rich experience","丰富经验"]],
"ride":[["ride a bike","骑车"],["give a ride","搭载"],["a smooth ride","平稳的行程"]],
"right":[["all right","好的"],["right now","现在"],["on the right","在右边"]],
"ring":[["the bell rings","铃响"],["ring back","回电"],["a diamond ring","钻戒"]],
"rise":[["rise early","早起"],["rise up","起来"],["a rise in price","涨价"]],
"river":[["by the river","在河边"],["cross the river","过河"],["a river of people","人潮"]],
"road":[["along the road","沿路"],["cross the road","过马路"],["on the road","在路上"]],
"room":[["make room","腾出空间"],["clean the room","打扫房间"],["room service","客房服务"]],
"rule":[["follow the rules","遵守规则"],["break a rule","违规"],["as a rule","通常"]],
"run":[["run away","跑开"],["run a shop","开店"],["run out of","用完"]],
"sad":[["sad news","悲伤的消息"],["feel sad","感到难过"],["sad to say","遗憾地说"]],
"safe":[["be safe","安全"],["safe and sound","安然无恙"],["play it safe","稳妥行事"]],
"salt":[["a bit of salt","一点盐"],["sea salt","海盐"],["worth one's salt","称职"]],
"same":[["the same as","与…相同"],["at the same time","同时"],["same old story","老一套"]],
"school":[["go to school","上学"],["after school","放学后"],["primary school","小学"]],
"science":[["science club","科学社"],["a science teacher","科学老师"],["science fiction","科幻"]],
"sea":[["by the sea","在海边"],["at sea","在海上"],["a sea of","一片"]],
"season":[["the dry season","旱季"],["in season","当季"],["out of season","过季"]],
"seat":[["take a seat","就座"],["all seats are available","座位全有"],["a front seat","前排座位"]],
"secret":[["keep a secret","保守秘密"],["a dark secret","隐秘"],["top secret","绝密"]],
"see":[["see you","再见"],["see a doctor","看医生"],["I see","我明白了"]],
"sell":[["sell out","卖光"],["sell well","畅销"],["sell the car","卖车"]],
"send":[["send a message","发消息"],["send for","派人去请"],["send up","发射"]],
"serve":[["serve the food","上菜"],["serve the people","为人民服务"],["serve as","充当"]],
"set":[["set up","建立"],["set off","出发"],["set a good example","树立好榜样"]],
"settle":[["settle down","安顿下来"],["settle a problem","解决问题"],["settle for","将就"]],
"shake":[["shake hands","握手"],["shake one's head","摇头"],["shake off","摆脱"]],
"shape":[["in good shape","状态好"],["take shape","成形"],["in the shape of","呈…形状"]],
"share":[["share a cake","分蛋糕"],["share with","与…分享"],["share an interest","有共同兴趣"]],
"shine":[["the cooker shines","炊具闪亮"],["shine on","照耀"],["take a shine to","一见钟情"]],
"ship":[["by ship","乘船"],["a cargo ship","货船"],["ship shape","井井有条"]],
"shirt":[["a white shirt","白衬衫"],["T-shirt","T恤"],["put on a shirt","穿上衬衫"]],
"shoe":[["drop her shoes","放下鞋"],["a pair of shoes","一双鞋"],["fill one's shoes","接替某人的位置"]],
"shop":[["a corner shop","街角小店"],["go shopping","购物"],["shop assistant","店员"]],
"short":[["a short one","短的"],["in short","简言之"],["run short","快用完"]],
"should":[["should do","应该做"],["you should go","你该去"],["should have done","本该做"]],
"shout":[["shout loudly","大声喊"],["shout for help","呼救"],["shout at","冲…喊"]],
"show":[["show me","给我看"],["show up","出现"],["art show","艺术展"]],
"shut":[["shut the book","合上书"],["shut up","闭嘴"],["shut the door","关门"]],
"shy":[["a shy smile","羞涩的笑"],["too shy to speak","害羞得不敢说话"],["shy away","躲避"]],
"sick":[["feel sick","感到恶心"],["sick leave","病假"],["be sick of","厌倦"]],
"side":[["on the other side","在另一边"],["side by side","肩并肩"],["take sides","站队"]],
"sight":[["at first sight","初见"],["lose sight of","看不见"],["out of sight","看不见"]],
"sign":[["a sign of","…的迹象"],["sign up","报名"],["sign one's name","签名"]],
"silence":[["in silence","沉默"],["break the silence","打破沉默"],["a silent agreement","无言的默契"]],
"silly":[["a silly question","傻问题"],["don't be silly","别傻了"],["silly joke","无聊的笑话"]],
"silver":[["a silver coin","银币"],["silver lining","一线希望"],["gold and silver","金银"]],
"simple":[["a simple life","简单的生活"],["simple words","简单的话"],["pure and simple","纯粹"]],
"since":[["ever since","自那以后"],["since then","从那以后"],["since childhood","从小"]],
"single":[["a single man","单身汉"],["every single day","每一天"],["single out","挑出"]],
"sir":[["sir, yes sir","是，长官"],["dear sir","尊敬的先生"],["excuse me, sir","先生，打扰一下"]],
"sister":[["my little sister","我妹妹"],["elder sister","姐姐"],["sister school","姐妹校"]],
"sit":[["sit down","坐下"],["sit up","坐直"],["sit at the desk","坐在书桌前"]],
"six":[["six o'clock","六点"],["at six","六点"],["six of one","半斤八两"]],
"size":[["the same size","同样大小"],["a size bigger","大一号"],["middle size","中号"]],
"skill":[["new skills","新技能"],["social skills","社交能力"],["a skilled worker","熟练工人"]],
"sky":[["in the sky","在天上"],["blue sky","蓝天"],["the sky's the limit","无上限"]],
"sleep":[["go to sleep","入睡"],["sleep well","睡得好"],["a sound sleep","酣睡"]],
"slow":[["slow down","减速"],["a slow train","慢车"],["slow and steady","稳扎稳打"]],
"small":[["a small shop","小店"],["small talk","寒暄"],["small world","世界真小"]],
"smell":[["smell good","闻起来香"],["the smell of","…的气味"],["smell a rat","起疑心"]],
"smile":[["smile at","微笑"],["a warm smile","温暖的微笑"],["smile from ear to ear","笑得合不拢嘴"]],
"smoke":[["no smoking","禁止吸烟"],["a cloud of smoke","一团烟"],["smoke free","无烟"]],
"smooth":[["smooth road","平坦的路"],["smooth skin","光滑的皮肤"],["smooth sailing","一帆风顺"]],
"snow":[["heavy snow","大雪"],["snow white","雪白"],["as clean as snow","洁白"]],
"soap":[["a bar of soap","一块肥皂"],["soap opera","肥皂剧"],["soap water","肥皂水"]],
"society":[["in modern society","在现代社会"],["a polite society","文明社会"],["society news","社会新闻"]],
"soft":[["a soft voice","轻柔的声音"],["soft drink","软饮料"],["soft heart","心软"]],
"soil":[["rich soil","肥沃的土壤"],["on the soil","在土地上"],["soil and water","水土"]],
"soldier":[["a toy soldier","玩具士兵"],["an old soldier","老兵"],["soldier on","坚持下去"]],
"son":[["her son","她儿子"],["like father like son","有其父必有其子"],["an only son","独子"]],
"song":[["a pop song","流行歌"],["sing a song","唱歌"],["theme song","主题曲"]],
"soon":[["as soon as","一…就"],["sooner or later","迟早"],["how soon","多快"]],
"sorry":[["I'm sorry","对不起"],["feel sorry for","为…感到遗憾"],["sorry to hear","很遗憾听到"]],
"sound":[["sound good","听起来不错"],["a strange sound","怪声"],["safe and sound","安然无恙"]],
"soup":[["a bowl of soup","一碗汤"],["beef soup","牛肉汤"],["dumpling soup","饺子汤"]],
"space":[["in space","在太空"],["make space","腾出空间"],["outer space","外太空"]],
"speak":[["speak English","说英语"],["speak up","大声说"],["generally speaking","一般而言"]],
"special":[["a special day","特别的一天"],["nothing special","没什么特别"],["special offer","特价"]],
"speech":[["give a speech","演讲"],["a short speech","简短讲话"],["make a speech","发表讲话"]],
"speed":[["at full speed","全速"],["speed up","加速"],["a fast speed","高速"]],
"spell":[["spell the word","拼写单词"],["spell out","详细说明"],["under a spell","被施了魔法"]],
"spend":[["spend money","花钱"],["spend time on","花时间在"],["spend the weekend","度周末"]],
"spirit":[["team spirit","团队精神"],["in high spirits","情绪高涨"],["the spirit of","…的精神"]],
"sport":[["do sports","做运动"],["a ball sport","球类运动"],["good at sports","擅长运动"]],
"spring":[["in spring","在春天"],["spring festival","春节"],["a spring in one's step","脚步轻快"]],
"stage":[["on the stage","在台上"],["a middle stage","中间阶段"],["stage by stage","逐步"]],
"stand":[["stand up","起立"],["stand for","代表"],["can't stand","无法忍受"]],
"star":[["a movie star","电影明星"],["starry sky","星空"],["see stars","眼冒金星"]],
"start":[["start with","以…开始"],["start school","开始上学"],["a fresh start","新开始"]],
"station":[["the train station","火车站"],["a space station","空间站"],["police station","警察局"]],
"stay":[["stay at home","待在家"],["stay up late","熬夜"],["stay calm","保持冷静"]],
"step":[["step by step","一步步"],["take a step","迈一步"],["a careless step","大意的一步"]],
"stone":[["a stone path","石径"],["kill two birds with one stone","一石二鸟"],["heart of stone","铁石心肠"]],
"stop":[["stop talking","别说话"],["stop by","顺路拜访"],["bus stop","公交站"]],
"store":[["a food store","食品店"],["store up","储备"],["in store","即将到来"]],
"storm":[["a heavy storm","暴风雨"],["brave the storm","顶风暴"],["a storm of applause","雷鸣般掌声"]],
"story":[["tell a story","讲故事"],["a funny story","有趣的故事"],["the story goes","据说"]],
"strange":[["a strange noise","怪声"],["a strange man","陌生人"],["strange enough","说来也怪"]],
"street":[["in the street","在街上"],["across the street","街对面"],["a quiet street","安静的街道"]],
"strong":[["a strong wind","强风"],["strong body","强壮的身体"],["strong coffee","浓咖啡"]],
"student":[["a college student","大学生"],["student card","学生证"],["exchange student","交换生"]],
"study":[["study hard","努力学习"],["study plan","学习计划"],["case study","案例研究"]],
"stupid":[["a stupid question","蠢问题"],["feel stupid","觉得傻"],["stupid idea","蠢主意"]],
"subject":[["a school subject","学校科目"],["change the subject","换个话题"],["on the subject of","关于"]],
"succeed":[["succeed in","成功"],["succeed to","继承"],["nothing succeeds like success","一举成功成功不断"]],
"success":[["a great success","巨大成功"],["the key to success","成功的关键"],["make a success of","把…做成功"]],
"such":[["such a good day","这么好的一天"],["such as","例如"],["no such thing","没有这种事"]],
"sudden":[["all of a sudden","突然"],["a sudden change","突变"],["sudden death","猝死"]],
"suffer":[["suffer from","患…病；受…苦"],["suffer a loss","蒙受损失"],["suffer in silence","默默忍受"]],
"sugar":[["a spoon of sugar","一勺糖"],["blood sugar","血糖"],["sugar free","无糖"]],
"suggest":[["suggest doing","建议做"],["as suggested","如建议"],["suggest a plan","提议计划"]],
"suit":[["a business suit","西装"],["suit yourself","随你便"],["suit the need","满足需要"]],
"summer":[["in summer","在夏天"],["summer camp","夏令营"],["summer holiday","暑假"]],
"sun":[["the sun rises","日出"],["in the sun","在阳光下"],["under the sun","天下"]],
"supper":[["have supper","吃晚饭"],["after supper","晚饭后"],["a light supper","简单晚饭"]],
"support":[["support the family","养家"],["support the plan","支持计划"],["with the support of","在…支持下"]],
"suppose":[["be supposed to","应该"],["I suppose so","我想是"],["suppose that","假设"]],
"sure":[["make sure","确保"],["be sure of","确信"],["sure enough","果然"]],
"surprise":[["a big surprise","大惊喜"],["in surprise","惊讶地"],["to one's surprise","令某人惊讶"]],
"sweet":[["sweet dreams","好梦"],["a sweet smile","甜美的微笑"],["sweet home","甜蜜的家"]],
"swim":[["go swimming","游泳"],["swim well","泳技好"],["swimming pool","游泳池"]],
"system":[["solar system","太阳系"],["a new system","新系统"],["system of a school","学校制度"]],
"table":[["at table","在用餐"],["a time table","时间表"],["table tennis","乒乓球"]],
"tail":[["a long tail","长尾巴"],["tail light","尾灯"],["can't make head or tail","摸不着头脑"]],
"take":[["take a break","休息"],["take care","保重"],["take place","发生"]],
"talk":[["talk about","谈论"],["talk to","与…交谈"],["talk over","商量"]],
"tall":[["a tall building","高楼"],["how tall","多高"],["walk tall","挺直腰杆"]],
"taste":[["taste good","尝起来好"],["a bitter taste","苦味"],["taste of home","家的味道"]],
"taxi":[["take a taxi","打的"],["call a taxi","叫出租车"],["taxi driver","出租车司机"]],
"tea":[["a cup of tea","一杯茶"],["green tea","绿茶"],["tea time","下午茶时间"]],
"teach":[["teach English","教英语"],["teach a lesson","教训"],["teach sb to do","教某人做"]],
"teacher":[["a good teacher","好老师"],["a science teacher","科学老师"],["ask the teacher","问老师"]],
"team":[["a basketball team","篮球队"],["team spirit","团队精神"],["on the same team","同一队"]],
"telephone":[["answer the telephone","接电话"],["by telephone","通过电话"],["telephone number","电话号码"]],
"television":[["watch television","看电视"],["on television","在电视上"],["colour television","彩色电视"]],
"tell":[["tell a story","讲故事"],["tell the truth","说实话"],["tell the difference","分辨"]],
"term":[["this term","这学期"],["in the long term","长期"],["in good terms","关系好"]],
"terrible":[["terrible news","可怕的消息"],["feel terrible","感到难受"],["a terrible cold","重感冒"]],
"test":[["a blood test","验血"],["test the water","试探"],["pass the test","通过测试"]],
"thank":[["thank you","谢谢"],["thanks to","多亏"],["thank goodness","谢天谢地"]],
"think":[["think of","想起"],["think about","考虑"],["think over","仔细考虑"]],
"though":[["as though","仿佛"],["even though","即使"],["though small","虽然小"]],
"thought":[["on second thought","转念一想"],["a happy thought","好想法"],["deep in thought","陷入沉思"]],
"through":[["go through","经历"],["through the window","透过窗"],["all through","一直"]],
"throw":[["throw away","扔掉"],["throw the ball","扔球"],["throw up","呕吐"]],
"ticket":[["a bus ticket","公交车票"],["a cheap ticket","便宜的票"],["one-way ticket","单程票"]],
"time":[["on time","准时"],["at the same time","同时"],["for the first time","第一次"]],
"tired":[["feel tired","感到累"],["tired of","厌倦"],["dead tired","累极了"]],
"today":[["today's paper","今天的报纸"],["up to today","到今天"],["today and tomorrow","今明两天"]],
"together":[["work together","一起工作"],["together with","连同"],["all together","一起"]],
"tomorrow":[["tomorrow morning","明早"],["see you tomorrow","明天见"],["tomorrow's plan","明天的计划"]],
"tonight":[["tonight's show","今晚的演出"],["stay home tonight","今晚待在家"],["not tonight","今晚不行"]],
"tooth":[["a sweet tooth","爱吃甜食"],["tooth ache","牙痛"],["brush one's teeth","刷牙"]],
"top":[["on top of","在…之上"],["at the top","在顶端"],["top student","尖子生"]],
"touch":[["keep in touch","保持联系"],["touch the screen","触屏"],["a gentle touch","温柔的触碰"]],
"tour":[["a school tour","学校参观"],["go on a tour","去旅行"],["tour guide","导游"]],
"town":[["go downtown","进城"],["home town","家乡"],["a small town","小镇"]],
"toy":[["a toy gun","玩具枪"],["toy soldiers","玩具士兵"],["toy shop","玩具店"]],
"traffic":[["heavy traffic","拥堵的交通"],["traffic light","红绿灯"],["traffic jam","堵车"]],
"train":[["train station","火车站"],["by train","坐火车"],["train hard","刻苦训练"]],
"travel":[["travel around","四处旅行"],["travel abroad","出国旅行"],["travel light","轻装旅行"]],
"treat":[["treat sb well","善待某人"],["treat a cold","治感冒"],["my treat","我请客"]],
"tree":[["under the tree","在树下"],["a tall tree","大树"],["family tree","家谱"]],
"trip":[["a school trip","学校郊游"],["a bus trip","公交之行"],["enjoy the trip","享受旅途"]],
"trouble":[["in trouble","有麻烦"],["trouble maker","捣蛋鬼"],["cause trouble","惹麻烦"]],
"truck":[["a fast truck","快速行驶的卡车"],["a heavy truck","重型卡车"],["truck driver","卡车司机"]],
"true":[["come true","实现"],["a true story","真实故事"],["true friend","真朋友"]],
"trust":[["trust yourself","相信自己"],["trust each other","互相信任"],["in trust","被托管"]],
"truth":[["tell the truth","说实话"],["find out the truth","查明真相"],["the bitter truth","残酷的真相"]],
"try":[["try on","试穿"],["try one's best","尽力"],["have a try","试一试"]],
"turn":[["turn left","左转"],["turn on","打开"],["in turn","依次"]],
"twice":[["twice a week","一周两次"],["think twice","三思"],["twice as much","两倍"]],
"understand":[["understand the words","理解词语"],["make yourself understood","让人理解"],["understand each other","相互理解"]],
"university":[["go to university","上大学"],["a university city","大学城"],["university life","大学生活"]],
"until":[["until late","直到很晚"],["not until","直到…才"],["until now","直到现在"]],
"up":[["get up","起床"],["up to you","由你决定"],["wake up","醒来"]],
"use":[["use your brain","动脑"],["make use of","利用"],["used to","过去常常"]],
"useful":[["a useful book","有用的书"],["useful skills","实用技能"],["come in useful","派上用场"]],
"vacation":[["on vacation","度假"],["a summer vacation","暑假"],["a short vacation","短暂假期"]],
"vegetable":[["fresh vegetables","新鲜蔬菜"],["vegetable soup","蔬菜汤"],["green vegetables","青菜"]],
"very":[["very good","很好"],["very much","非常"],["at the very end","在最后"]],
"victory":[["win a victory","赢得胜利"],["a great victory","大捷"],["victory day","胜利日"]],
"village":[["a small village","小村庄"],["in the village","在村里"],["village life","乡村生活"]],
"visit":[["visit friends","拜访朋友"],["a school visit","参观学校"],["pay a visit","拜访"]],
"voice":[["in a low voice","低声"],["a sweet voice","甜美嗓音"],["lose one's voice","失声"]],
"wait":[["wait for","等待"],["can't wait","迫不及待"],["wait a moment","稍等"]],
"wake":[["wake up","醒来"],["wake at once","立刻醒来"],["stay awake","保持清醒"]],
"walk":[["walk to school","走路上学"],["take a walk","散步"],["walk home","走回家"]],
"wall":[["on the wall","在墙上"],["a city wall","城墙"],["wall paper","墙纸"]],
"want":[["want to do","想做"],["want a go","想试试"],["what you want","你想要的"]],
"war":[["World War Two","二战"],["at war","交战"],["the cold war","冷战"]],
"warm":[["a warm coat","暖外套"],["warm up","热身"],["warm heart","热心"]],
"wash":[["wash hands","洗手"],["wash away","冲走"],["do the washing","洗衣服"]],
"waste":[["waste time","浪费时间"],["a waste of","对…的浪费"],["waste paper","废纸"]],
"watch":[["watch TV","看电视"],["watch out","小心"],["a watch","手表"]],
"water":[["drink water","喝水"],["by water","走水路"],["water the flowers","浇花"]],
"way":[["by the way","顺便说"],["on the way","在路上"],["in a way","在某种程度上"]],
"weather":[["weather report","天气预报"],["in all weathers","无论天气如何"],["fine weather","好天气"]],
"week":[["last week","上周"],["every week","每周"],["week by week","逐周"]],
"welcome":[["welcome to","欢迎来到"],["you're welcome","不客气"],["a welcome guest","受欢迎的客人"]],
"well":[["as well","也"],["do well","做得好"],["as well as","以及"]],
"west":[["in the west","在西部"],["go west","去西部"],["the west wind","西风"]],
"white":[["a white shirt","白衬衫"],["white collar","白领"],["as white as snow","雪白"]],
"whole":[["the whole class","全班"],["as a whole","整体"],["a whole day","一整天"]],
"why":[["why not","为什么不"],["the reason why","…的原因"],["no reason why","没有理由"]],
"wide":[["a wide road","宽路"],["far and wide","广泛"],["world-wide","世界范围"]],
"wife":[["his wife","他妻子"],["husband and wife","夫妻"],["a good wife","贤妻"]],
"wind":[["the wind blows","风吹"],["in the wind","即将发生"],["strong wind","强风"]],
"window":[["by the window","在窗边"],["open the window","开窗"],["window seat","靠窗座位"]],
"winter":[["in winter","在冬天"],["cold winter","寒冬"],["winter holiday","寒假"]],
"wise":[["a wise man","智者"],["wise choice","明智选择"],["wise up","明白过来"]],
"wish":[["wish you well","祝你好运"],["make a wish","许愿"],["best wishes","美好的祝愿"]],
"without":[["without doubt","无疑"],["go without","没有也行"],["do without","将就"]],
"woman":[["a kind woman","善良的女人"],["women and children","妇女儿童"],["a grown woman","成年女子"]],
"wood":[["a bamboo wood","竹林"],["out of the woods","脱离险境"],["wooden box","木盒"]],
"word":[["in other words","换句话说"],["a word of advice","一句忠告"],["keep one's word","守信"]],
"work":[["at work","在工作"],["work hard","努力工作"],["work out","解决；锻炼"]],
"world":[["around the world","全世界"],["the outside world","外面的世界"],["make a world of difference","天壤之别"]],
"worry":[["don't worry","别担心"],["worry about","担心"],["worried sick","担心坏了"]],
"write":[["write a letter","写信"],["write down","写下"],["write about","写关于"]],
"wrong":[["go wrong","出问题"],["the wrong way","错误方式"],["in the wrong","理亏"]],
"year":[["this year","今年"],["year by year","逐年"],["all year round","一年到头"]],
"young":[["a young man","年轻人"],["young and old","老少"],["forever young","永葆青春"]]
};